### ISSUE TITLE
[FFDev][macOS] Unable to setup extension

### ISSUE THREAD

**Issue by snwflake** [varjolintu/keepassxc-browser#22]
### Steps:

1. install your fork and setup
2. download proxy and setup
3. download browser extension
4. open keepassxc
5. open FF, proxy starts, so far so good.
6. extension yields: `keepassxc-browser has not been configured. Press the connect button to register and pair with KeePassXC.`
7. clicking "Connect"
8. "New association request for above key......."
9. giving it UUID and press "OK"
10. Entry appears on top of my db in root
11. browser extension now "Checking status" and soon switching to `Not connected with KeePassXC`
12. Proxy now receiving only timeouts, with action `get-databasehash`

### Versions:
* macOS Sierra 10.12.5
* FF Developer Edition 57.0b2
* FF Extension 0.3.0
* KeePassXC Forked 2.2.0
* varjolintu/keepassxc-proxy@009912ce6f27c0f1074a9bbafae65931572b2412

**Comment by snwflake** [comment]
Apparently, KeePassXC wasn't satisfied by my unique identifier...Is there any requirement in term of min length, allowed characters?
E.g. 
`TOTALLY_UNIQUE` didn't succeed, but `dfgdfgdgdgdfgdgdg` did..... 🤔

**Comment by varjolintu** [comment]
And this behaviour in your latest message happens with or without a proxy? The unique identifer is just a normal QString without restrictions. I will check this issue.

**Comment by snwflake** [comment]
I was using the proxy app. Wouldn't want to test it w/o the proxy, since I want to use KeePassXC without the browser aswell.
Going to test an older version. Do you have a specific sha? Since there are no releases :)

**Comment by snwflake** [comment]
Hi Sami, a little update:
FF updated to 57.0b3
Switched to the C++ proxy.

2.2.0-browser-beta8 is working just fine.

Tried RC1 with the C++ proxy, but those two won't work together at all.

Let me know  if I can provide additional information!
Cheers

**Comment by varjolintu** [comment]
@snwflake Thank you for the info. Yesterday I ran to some problems with the RC1 release and made some changes. Could you try the KeePassXC-2.2.0-browser-nightly270917.dmg from the releases page I just uploaded? It works for me.

**Comment by snwflake** [comment]
Unfortunately no change. It seems like it doesn't get recognized by either the proxy or the browser extension. 

_`Your running version of KeePassXC: unknown`_

```
keepassxc-browser has encountered an error:
Cannot decrypt message
```
Also button clicks (e.g. Reopen Database) don't bring KeePassXC to the front, as with the older version.

**Comment by varjolintu** [comment]
Hmm. Maybe the package didn't get updated after all. Please test the new KeePassXC-2.2.0-browser-dev290917.dmg

**Comment by varjolintu** [comment]
The latest version of keepassxc-browser extension 0.3.1 will add support for timeouts, so the proxy applications will work even better in the future.

**Comment by snwflake** [comment]
Updated the browser-extension to 0.3.1 and also tested the dev-built to no avail. 
I started looking into the problem a bit more, and found that there was no traffic on the UDP port (UDP:14333 in my case).

**Comment by varjolintu** [comment]
Please use the default port 19700 until there's a support for port changing in the proxy app.

**Comment by snwflake** [comment]
I changed the port.

**Comment by varjolintu** [comment]
Please wait for the RC2 release. There's a few issues I've found.

**Comment by varjolintu** [comment]
Check the new RC2 build and report if you still have any problems :)

**Comment by snwflake** [comment]
The good news: the extension now recognizes when KeePassXC is running (at least theres a version number displayed in the settings).
The bad news, they still can't interact with each other.

The default message is `Cannot decrypt message` which changes to 
```
keepassxc-browser has encountered an error:

5
```

That would then translate to `Timeout or not connected to KeePassXC`. You probably should look into that aswell ;)

Allthough, killing FF brings KeePassXC to the front, even if minimized to menubar, so thats an improvement I guess.

**Comment by varjolintu** [comment]
Could you debug where that error message comes from? I cannot reproduce the problem.

**Comment by snwflake** [comment]
Sure, gonna get into how those browser extensions work in general.

**Comment by varjolintu** [comment]
Check the updated keepassxc-proxy and latest [dev-release](https://github.com/varjolintu/keepassxc/releases/download/2.2.0-browser-rc2/KeePassXC-2.2.0-browser-dev111017.dmg) if possible :)

**Comment by snwflake** [comment]
Thanks for providing this.
At first, the extensions state was `Cannot encrypt message or public key not found`. I went to the settings page and tried connecting a db, which brought KeePassXC to the front. Adding a db-relation worked, but the extensions state didn't change. After killing the browser, the extension went to another state `You use an old version of KeePassXC.` and the spinning `Checking status`

**Comment by varjolintu** [comment]
So you didn't use the Reload button from the popup? If it wasn't visible (or there was a button named Reopen database) the issue is fixed with the browser extension version 0.3.3 which is going to be online pretty soon.

I think I finally know why this issue happens. I will upload another dev build for you to try later today.

**Comment by snwflake** [comment]
The reload button does nothing. It never did anything while using the proxy. Even though I can add a new db-relation (which, btw, doesn't always work) the "checking status" still won't resolve.

I spent a good amount of time digging through the code tonight (especially the diff from 2.2.0-beta8 and 2.2.0-rc.1/2) since beta8 is working totally fine. But I couldn't figure out a difference (in code) that would explain, or even avert this kind of behavior. I'm not really into js, so that fell of the short end.

**Comment by varjolintu** [comment]
When not using the proxy, reload button should open KeePassXC. When using the proxy, reload button reloads the proxy application.

The problem with the latest dev build is that testAssociate doesn't return a error message when corresponding key is not found or is different. I fixed it already and it is in the branch sources but the build image isn't yet updated.

I'm using the dev version of KeePassXC branch and keepassxc-proxy daily so I can squash the bugs pretty quickly, but this has been a nasty one :) The problem showed again after the feature I just added (you can simultaneously connect multiple browsers to one opened database with proxy) because it changed the source code quite a lot. I really hope this bug is finally getting fixed.

You have been a great help. Thank you a lot.

**Comment by varjolintu** [comment]
New extension version 0.3.3 is released. It should work nicely with [this](https://github.com/varjolintu/keepassxc/releases/download/2.2.0-browser-rc2/KeePassXC-2.2.0-browser-dev131017.dmg) dev release that is probably going to be the rc3 build. Please try it.

**Comment by snwflake** [comment]
Hi and thanks! It's finally working as expected :)
The dev build did not though. Had to build the feature branch myself in order to get it working. Don't know why.

Do you have an ETA on when your PR gets merged into the main repo?

**Comment by varjolintu** [comment]
Glad it works. But of course it's strange if the build I made didn't work.. It's the same code after all.

The ETA is after KeePassXC 2.2.2 and before 2.3.0. So don't know the exact time yet :)
