### ISSUE TITLE
0.3.8 lost database connection, stuck in "Checking Status"

### ISSUE THREAD

**Issue by whisdol** [varjolintu/keepassxc-browser#33]
I'm using KeePassXC-Browser 0.3.8 in Firefox Nightly 58.0a1 (2017-11-03) and KeePassXC 2.2.0 Browser RC 4 on Windows 10, and since the extension update (or maybe before), I'm unable to connect to the database.
The extension icon just shows "Checking status" (and prompts me to update KeePassXC, but that's probably unrelated).
In the extension settings, the entry for my previously connected database is now gone and the list is empty. When clicking the "Connect"-button, the button stays "active" (dark blue), but nothing else happens.

KeePassXC starts with Firefox, and the browser support is enabled in KeePassXC. An older version of the extensions has worked with RC4 and I did not change any settings.

This is the debugging output:

> Could not map contract ID '@mozilla.org/fxaccounts/push;1' to CID {1b7db999-2ecd-4abf-bb95-a726896798ca} because no implementation of the CID is registered.  components.manifest:177
> Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user’s experience. For more help http://xhr.spec.whatwg.org/  background.js:5:173
> Error 5: Timeout or not connected to KeePassXC  keepass.js:853:2
> Connecting to native messaging host com.varjolintu.keepassxc_browser  keepass.js:799:2
> Error 7: Cannot encrypt message or public key not found. Is Native Messaging enabled in KeePassXC? keepass.js:853:2
> Server public key: dliJwDJ536GAeDsBlnNIW0xnGthlvBtJ9kHzWZPpVwM= keepass.js:576:5
> Error 1: Database not opened keepass.js:853:2
> Error: Promised response from onMessage listener at @moz-extension://b7c57be3-568b-4a35-ac13-f6e3e55b2180/background/init.js:92:1 went out of scope  undefined
> Source map error: TypeError: NetworkError when attempting to fetch resource.
> Resource URL: moz-extension://b7c57be3-568b-4a35-ac13-f6e3e55b2180/options/bootstrap.min.css
> Source Map URL: bootstrap.min.css.map[Learn More]  (unknown)
> Use of nsIFile in content process is deprecated. NetUtil.jsm:307:12
> Error: Promised response from onMessage listener at @moz-extension://b7c57be3-568b-4a35-ac13-f6e3e55b2180/background/init.js:92:1 went out of scope

**Comment by varjolintu** [comment]
Have you tried disabling and enabling the extension? And can you check from the extension settings if your database is still shown there? There are some changes with the local storage implementation so if there's anything please run browser.storage.local.clear() from the JavaScript console (available through about:debugging).

**Comment by whisdol** [comment]
The list of connected databases is empty.
KeePassXC went unresponsive the first time I tried to disable it. After force closing, I was able to disable and re-enable it. I did that a couple of times with restarts in between, but the issue persists.
I also cleared the Local Storage, but that also did not help. The error messages in the debug log stay the same.

**Comment by varjolintu** [comment]
Is there any difference if you use an older RC? I'm pretty close releasing another RC but I'll check the behaviour tomorrow with Windows.

**Comment by whisdol** [comment]
I don't think the main app is the issue as the RC4 worked before.
I reinstalled version 0.3.6 and 0.3.7 from the Mozilla addons page, and both work correctly and are able to connect to the database. After upgrading again to 0.3.8, I get the same problem and the extension is stuck in "Checking status".

**Comment by ishitatsuyuki** [comment]
I have already tried wiping local storage, but the problem persists. My browser log (contains some offline junk):

```
[Exception... "Component returned failure code: 0xc1f30001 (NS_ERROR_NOT_INITIALIZED) [nsIMessageSender.sendAsyncMessage]"  nsresult: "0xc1f30001 (NS_ERROR_NOT_INITIALIZED)"  location: "JS frame :: resource://gre/modules/ExtensionUtils.jsm :: sendAsyncMessage :: line 505"  data: no]  (unknown)
"Handler function threw an exception: TypeError: this.transport is null
Stack: send@resource://devtools/shared/base-loader.js -> resource://devtools/server/main.js:1514:5
addSecurityInfo@resource://devtools/shared/base-loader.js -> resource://devtools/server/actors/webconsole.js:2254:5
NetworkResponseListener.prototype._getSecurityInfo<@resource://devtools/shared/base-loader.js -> resource://devtools/shared/webconsole/network-monitor.js:495:5
exports.makeInfallible/<@resource://devtools/shared/base-loader.js -> resource://devtools/shared/ThreadSafeDevToolsUtils.js:109:14
onStartRequest@resource://devtools/shared/base-loader.js -> resource://devtools/shared/webconsole/network-monitor.js:436:5
Line: 1514, column: 5"  ThreadSafeDevToolsUtils.js:88
TypeError: this.transport is null[Learn More]  main.js:1514:5
[Exception... "Component returned failure code: 0xc1f30001 (NS_ERROR_NOT_INITIALIZED) [nsIMessageSender.sendAsyncMessage]"  nsresult: "0xc1f30001 (NS_ERROR_NOT_INITIALIZED)"  location: "JS frame :: resource://gre/modules/ExtensionUtils.jsm :: sendAsyncMessage :: line 505"  data: no]  (unknown)
TypeError: subject is null[Learn More]  forms.js:238:15
1509762279786	Toolkit.Telemetry	ERROR	TelemetrySend::sendPersistedPings - failed to send ping 14cf9d70-ca56-465b-91a9-0010e1a438d0: {"name":"PingReadError","message":"","stack":"PingReadError@resource://gre/modules/TelemetryStorage.jsm:81:15\nloadPingFile@resource://gre/modules/TelemetryStorage.jsm:1679:13\n","becauseNoSuchFile":true}  Log.jsm:752
Sync encountered an error - see about:sync-log for the log file.  policies.js:773
Content Security Policy: Ignoring ‘x-frame-options’ because of ‘frame-ancestors’ directive.  (unknown)
Content Security Policy: The page’s settings blocked the loading of a resource at self (“script-src https://assets-cdn.github.com”). Source: ;(function installHook (window) {
  var ....  keepassxc-browser:1
Empty string passed to getElementById().  github-fe7eef78cc7848d03a0d5811c0d1b9c058ad00cad2bac68b9b7c5bac083b8410.js:8:1281
Content Security Policy: The page’s settings blocked the loading of a resource at self (“script-src https://assets-cdn.github.com”). Source: ;(function detect (win) {
  setTimeout(f....  keepassxc-browser:1
Error: Promised response from onMessage listener at @moz-extension://a355b7b8-1739-4431-9054-e3d424c93f2d/background/init.js:92:1 went out of scope  undefined
TypeError: select_dom_default(...)(...) is null  content.js:1804:21
TypeError: select_dom_default(...)(...) is null  content.js:1275:19
Error: Promised response from onMessage listener at @moz-extension://a355b7b8-1739-4431-9054-e3d424c93f2d/background/init.js:92:1 went out of scope  undefined
Error 5: Timeout or not connected to KeePassXC  keepass.js:853
[Exception... "Component returned failure code: 0xc1f30001 (NS_ERROR_NOT_INITIALIZED) [nsIMessageSender.sendAsyncMessage]"  nsresult: "0xc1f30001 (NS_ERROR_NOT_INITIALIZED)"  location: "JS frame :: resource://gre/modules/ExtensionUtils.jsm :: sendAsyncMessage :: line 505"  data: no]  (unknown)
Error 5: Timeout or not connected to KeePassXC  keepass.js:853
```

**Comment by varjolintu** [comment]
Fixed with release 0.3.9. It should be available soon at AMO and Chrome Web Store.

**Comment by whisdol** [comment]
0.3.9 unfortunately does not fix this for me with Firefox on Windows 10, it's still "Checking status" and clicking the connect button does not do anything. The debug output still looks very similar:

> Could not map contract ID '@mozilla.org/fxaccounts/push;1' to CID {1b7db999-2ecd-4abf-bb95-a726896798ca} because no implementation of the CID is registered.  components.manifest:177
> Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user’s experience. For more help http://xhr.spec.whatwg.org/  background.js:5:173
> Error 5: Timeout or not connected to KeePassXC  keepass.js:853:2
> Connecting to native messaging host com.varjolintu.keepassxc_browser  keepass.js:799:2
> Error 7: Cannot encrypt message or public key not found. Is Native Messaging enabled in KeePassXC?  keepass.js:853:2
> Server public key: 9i16y3j406m2eBu1bz0DLNmtbs7/HwSZyuZCuov+6A4= keepass.js:576:5
> Error 1: Database not opened keepass.js:853:2
> Use of nsIFile in content process is deprecated. NetUtil.jsm:307:12
> Source map error: TypeError: NetworkError when attempting to fetch resource.
> Resource URL: moz-extension://b7c57be3-568b-4a35-ac13-f6e3e55b2180/options/bootstrap.min.css
> Source Map URL: bootstrap.min.css.map[Learn More]  (unknown)
> Error: Promised response from onMessage listener at @moz-extension://b7c57be3-568b-4a35-ac13-f6e3e55b2180/background/init.js:92:1 went out of scope  undefined
> Source map error: TypeError: NetworkError when attempting to fetch resource.
> Resource URL: moz-extension://b7c57be3-568b-4a35-ac13-f6e3e55b2180/options/bootstrap.min.css
> Source Map URL: bootstrap.min.css.map[Learn More]  (unknown)
> Error: Promised response from onMessage listener at @moz-extension://b7c57be3-568b-4a35-ac13-f6e3e55b2180/background/init.js:92:1 went out of scope

Everything works on macOS, though.

**Comment by varjolintu** [comment]
I just tested this with Windows 10, RC4 build with both Firefox 56 stable and 58 nightly and both worked without any problems.

Are you sure this isn't related to Firefox Nightly? I used it sometimes while developing and noticed that some day it just might be broken and suddenly everything works another day.

**Comment by whisdol** [comment]
I'm not sure what the issue was, but I deleted the registry keys manually, installed RC5, enabled the extension support again and now it works as expected.
Thanks!
